### ISSUE TITLE
Especificaciones Despliegue

### ISSUE THREAD

**Issue by reyescuesta2** [samubp10/SpaceBP#2]
https://github.com/IESCampanillas/proyectos-daw-2022/wiki/Despliegue-de-Aplicaciones-Web
Necesito que me especifiques en el anteproyecto que vas a usar para el despliegue de la aplicación en la nube. En concreto:
Desplegar la aplicación en la nube: En que servidor en la nube vas a desplegarla?
Dominio: Que dominio vas a utilizar o donde lo vas a conseguir?
SGBD: Vas a alojar la base de datos donde mismo que la web o en un servidor aparte?

**Comment by samubp10** [comment]
Hola buenas, ya he añadido al anteproyecto las especificaciones que me ha
pedido. Si están mal o no es suficiente, notifíquemelo por favor.

**Comment by reyescuesta2** [comment]
Buenas Samuel, no me aparece el cambio en el readme de tu proyecto. ¿Puedes indicarme donde has añadido el cambio?

**Comment by reyescuesta2** [comment]
todo completo
